### ISSUE TITLE
Negative letter spacing makes font hard to read

### ISSUE THREAD

**Issue by Chatanga** [gradle-guides/style-guide#4]
The CSS used for the various guides uses a negative letter-spacing of -0.01em, making the Lato font hard to read. With Firefox running on Linux at least, words are not clearly separated and characters sometimes overlap. Per instance, the "ce" in "since" is displayed the same way as the french "œ" which is especially confusing because "œ" = "o+e".

**Comment by lacasseio** [comment]
Moved to https://github.com/gradle/guides/issues/310
